version: 0.0
os: linux
files:
  - source: build/
    destination: /home/ec2-user/coopui
hooks:
  BeforeInstall:
    - location: scripts/aws/delete.sh
      timeout: 300
  AfterInstall:
    - location: scripts/aws/copy-static.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/aws/start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/aws/shutdown.sh
      timeout: 300